import { NextResponse } from "next/server";

/**
 * Server-side proxy to the Venice AI API (OpenAI-compatible).
 * Keeps VENICE_API_KEY on the server. Falls back to a deterministic
 * mock so the app always runs, even without a key.
 *
 * Docs: https://docs.venice.ai  base: https://api.venice.ai/api/v1
 */

const VENICE_BASE = process.env.VENICE_BASE_URL || "https://api.venice.ai/api/v1";
const VENICE_MODEL = process.env.VENICE_MODEL || "llama-3.3-70b";

type Msg = { role: "system" | "user" | "assistant"; content: string };

export async function POST(req: Request) {
  const body = (await req.json()) as {
    messages: Msg[];
    json?: boolean;
    temperature?: number;
  };
  const key = process.env.VENICE_API_KEY;

  if (!key) {
    return NextResponse.json({
      text: mockResponse(body.messages, body.json),
      model: "mock-venice",
      mode: "mock",
    });
  }

  try {
    const res = await fetch(`${VENICE_BASE}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({
        model: VENICE_MODEL,
        messages: body.messages,
        temperature: body.temperature ?? 0.6,
        ...(body.json ? { response_format: { type: "json_object" } } : {}),
        venice_parameters: { include_venice_system_prompt: false },
      }),
    });

    if (!res.ok) {
      const errText = await res.text();
      return NextResponse.json({
        text: mockResponse(body.messages, body.json),
        model: "mock-venice",
        mode: "mock",
        note: `Venice API error ${res.status}: ${errText.slice(0, 140)}; using fallback`,
      });
    }

    const data = await res.json();
    const text = data?.choices?.[0]?.message?.content ?? "";
    return NextResponse.json({ text, model: data?.model ?? VENICE_MODEL, mode: "real" });
  } catch (e) {
    return NextResponse.json({
      text: mockResponse(body.messages, body.json),
      model: "mock-venice",
      mode: "mock",
      note: `Venice request failed: ${(e as Error).message}; using fallback`,
    });
  }
}

/** Deterministic, context-aware mock so demos work without a key. */
function mockResponse(messages: Msg[], json?: boolean): string {
  const last = messages[messages.length - 1]?.content ?? "";
  const lower = last.toLowerCase();

  if (json && lower.includes("plan")) {
    return JSON.stringify({
      summary:
        "Assess short-term risk; use free data first, buy paid sentiment only if it materially improves confidence and the price is within the covenant limit.",
      steps: [
        "Pull free on-chain + price data for the asset.",
        "Estimate whether free signal is sufficient for a risk call.",
        "If not, request a paid sentiment report via an x402 service.",
        "Validate the x402 quote against the covenant policy before paying.",
        "Summarize findings into a final risk report with sources and cost.",
      ],
      needsPaidData: true,
      maxAcceptablePrice: 0.5,
    });
  }

  if (lower.includes("risk report") || lower.includes("final report")) {
    return [
      "## Risk Assessment",
      "",
      "**Verdict:** Medium short-term risk.",
      "",
      "Free price and on-chain activity were inconclusive on their own, so a paid sentiment report was purchased under the covenant. Social sentiment is mildly negative with elevated derivative funding, consistent with a short-term pullback risk, but no structural red flags.",
      "",
      "- Liquidity: healthy",
      "- Sentiment: slightly negative (paid signal)",
      "- Volatility: elevated",
      "",
      "_Generated by the agent using free data + one policy-approved paid datapoint._",
    ].join("\n");
  }

  return "The agent evaluated the request and proceeded within the bounds of the active covenant.";
}
